<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="*" />
    <PackageVersion Include="Bogus" Version="*" />
    <PackageVersion Include="ConcurrentHashSet" Version="*" />
    <PackageVersion Include="csbindgen" Version="*" />
    <PackageVersion Include="CSharpier.MsBuild" Version="*" />
    <PackageVersion Include="Dahomey.Cbor" Version="*" />
    <PackageVersion Include="DotNet.ReproducibleBuilds" Version="*" />
    <PackageVersion Include="FluentAssertions" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.JsonPatch.SystemTextJson" Version="*" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.3" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="*" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="*" />
    <PackageVersion Include="Microsoft.Extensions.ObjectPool" Version="*" />
    <PackageVersion Include="Microsoft.IO.RecyclableMemoryStream" Version="*" />
    <PackageVersion Include="Microsoft.OpenApi" Version="*" />
    <PackageVersion Include="Microsoft.Reactive.Testing" Version="*" />
    <PackageVersion Include="Microsoft.Spatial" Version="*" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.5.2" />
    <PackageVersion Include="MudBlazor" Version="*" />
    <PackageVersion Include="Pidgin" Version="*" />
    <PackageVersion Include="Scalar.AspNetCore" Version="*" />
    <PackageVersion Include="Semver" Version="*" />
    <PackageVersion Include="Superpower" Version="*" />
    <PackageVersion Include="Swashbuckle.AspNetCore" Version="*" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="*" />
    <PackageVersion Include="System.Collections.Immutable" Version="*" />
    <PackageVersion Include="System.Interactive.Async" Version="*" />
    <PackageVersion Include="System.Linq.Async" Version="*" />
    <PackageVersion Include="System.Linq.AsyncEnumerable" Version="*" />
    <PackageVersion Include="SystemTextJsonPatch" Version="*" />
    <PackageVersion Include="TUnit" Version="*" />
    <PackageVersion Include="Ulid" Version="*" />
    <PackageVersion Include="Verify.TUnit" Version="*" />
    <PackageVersion Include="Websocket.Client" Version="*" />
  </ItemGroup>
</Project>